const { db } = require("../db");

/**
 * The callback function for the /api/listPuzzles GET route.
 *
 * The `res` parameter should return an array of JSON objects containing puzzle data.
 * @param {Express.Request} req - The Request object generated by the route.
 * @param {Express.Response} res - The Result object generated by the route.
 * @returns Nothing.
 */
function listPuzzles(req, res) {
  const { userID, username } = req.session;

  db.all(`SELECT * FROM Puzzle`, (err, rows) => {
    if (err) {
      res.status(500).send(err);
    } else {
      res.status(200).send({
        userID,
        username,
        rows
      });
    }
  });
}

module.exports = { listPuzzles };
