const { db } = require("../db");

/**
 * The callback function for the /api/listPuzzles GET route.
 *
 * The `res` parameter should return an array of JSON objects containing puzzle data.
 * @param {Express.Request} req - The Request object generated by the route.
 * @param {Express.Response} res - The Result object generated by the route.
 * @returns Nothing.
 */
function listPuzzles(req, res) {
  const { userID, username } = req.session;

  //up.progress, p.puzzle_id, p.title, p.description

  const puzzleListQuery = `
      SELECT *
      FROM Puzzle
    `;

  const userPuzzleCompletionQuery = `
    SELECT progress, puzzle_id 
    FROM User_Puzzle
    WHERE user_id = ${userID}
    `;

  db.all(puzzleListQuery, (err, rows) => {
    if (err) {
      res.status(500).send(err);
    } else {
      // sort the rows by puzzle ID
      rows = rows.sort((a, b) => { return a.puzzle_id - b.puzzle_id })

      db.all(userPuzzleCompletionQuery, (err, userPuzzleCompletion) => {
        if (err) {
          res.status(500).send(err)
        } else {
          // sort by puzzle ID
          userPuzzleCompletion = userPuzzleCompletion.sort((a, b) => { return a.puzzle_id - b.puzzle_id})

          res.status(200).send({
            userID,
            username,
            puzzles: rows,
            userPuzzleCompletion
          });
        }
      });
    }
  });
}

module.exports = { listPuzzles };
