const Express = require('express')
const db = require('../db');

/**
 * The callback function for the /api/ListPuzzles GET route.
 *
 * The `res` parameter should return an array of JSON objects containing puzzle data.
 * @param {Express.Request} req - The Request object generated by the route.
 * @param {Express.Response} res - The Result object generated by the route.
 * @returns Nothing.
 */
function getPuzzles(req, res) {
    db.all(`SELECT * FROM Puzzle`, (err, rows) => {
        if (err) {
            res.status(500).send(err);
            return next(err);
        } else if (res.headersSent !== true) {
            //console.log(`Title: ${row.title}, Desc: ${row.description}`);
            res.status(200).send(rows);
        }
    });
}

module.exports = getPuzzles