/**
 * The callback function for the /api/signup POST route. Logs out a user, 
 * then sends them to the homepage with a message telling them they are logged out.
 *
 * Under the hood, this calls req.session.destroy().
 * @param {Express.Request} req - The Request object generated by the route.
 * @param {Express.Response} res - The Response object generated by the route.
 * @param {Function} next - The next() function used in the callback.
 * @returns Nothing.
 */
function logout(req, res, next) {
  // can't destroy a session if it doesn't exist
  req.session?.destroy((err) => {
    if (err) {
      res.status(500).send(err);
      return;
    }

    // TODO: find a way to pass info to the homepage
    res.redirect("/");
  });
}

module.exports = { logout };
