name: Assign PR Reviewers

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }} # assign pull request author
          reviewers: Blackkirby72, connormckellips, kantab, kreklb, lmschaff, Maxwell1455, prewe5294, PistolRcks
          max-num-of-reviewers: 2