name: Continuous Integration 

on:
  pull_request:
    branches: [ "master" ]

jobs:
  npm_test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create and Populate dotenv 
      run: |
        touch .env
        echo GOOGLE_OAUTH_CLIENTID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }} >> .env
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test