name: Glitch Sync on PR Merge

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  sync_on_merge:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: kanadgupta/glitch-sync@main
        with:
          auth-token: '${{ secrets.GLITCH_AUTH_TOKEN }}'
          project-id: '${{ secrets.GLITCH_PROJECT_ID }}'
